version: '3'
services:
  python:
    container_name: tsp-docker
    platform: linux/amd64
    build:
      context: .
    volumes:
      - ./src:/project/src
      - ./lib:/project/lib
      - ./results:/project/results
    tty: true